DEBUG 2022-07-28 10:46:48.745 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-07-28 10:46:48.745 UTC: 	 Running on: Linux lxplus715.cern.ch 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-07-28 10:46:48.745 UTC: 	 Executing command: 'status'
DEBUG 2022-07-28 10:46:48.745 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ryi/.crab3
ERROR 2022-07-28 10:46:48.746 UTC: 	 Error: crab_2016B-pre-7-27-2022/crab_UL2016preVFP_Run2016B_ver2 is not a valid CRAB project directory.
ERROR 2022-07-28 10:46:48.746 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_2016B-pre-7-27-2022/crab_UL2016preVFP_Run2016B_ver2 is not a valid CRAB project directory.
INFO 2022-07-28 10:46:48.780 UTC: 	 Log file is /afs/cern.ch/user/r/ryi/test/CMSSW_10_6_13/src/EgammaAnalysis/TnPTreeProducer/crab.log
